services:
 nginx:
  depends_on:
   - wordpress
   - mariadb
  build: requirements/nginx/.
  container_name: nginx
  ports: 
      - "8080:80"
  volumes:
      - ./web:/var/www/html
  networks:
      inception:
 wordpress:
  depends_on: 
   - mariadb
  build: requirements/wordpress/. # where to find the dockerfile that tells us how the image is build
  container_name: wordpress # how to name the container
  volumes:
      - ./web:/var/www/html
  networks:
      inception:
 mariadb:
  build: requirements/mariadb/.
  container_name: mariadb
  volumes: 
      - ./database:/var/lib/mysql
  networks:
      inception:


networks:
      inception:
  
  


  
