services:
 nginx:
  depends_on:
   - wordpress
  build: requirements/nginx/.
  container_name: nginx
  ports: 
      - "8080:80"
  volumes:
      - ./web:/var/www/html

 wordpress:
  build: requirements/wordpress/. # where to find the dockerfile that tells us how the image is build
  container_name: wordpress # how to name the container
  volumes:
      - ./web:/var/www/html


  
