location ~ \.php$ { #everything ending on .php will be handled here (~ -> regular expression)
    include fastcgi_params; #loads standard list of variables needed to talk to php-fpm (interpreter)
    fastcgi_pass wordpress:9000; # fastcgi_pass is a directive (like root or listen) and forwards the request to another process -> in this case to: wordpress (like a hostname):9000(port) (cause nginx can't run php itself -> needs wordpress to do it)
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; #tells us which exacy php file on disk to run
}
